### ISSUE TITLE
Undefinded Methods

### ISSUE THREAD

**Issue by codersangam** [habibmhamadi/laravel8-blog-api#1]
In line number 55 `'token' => auth()->user()->createToken('secret')->plainTextToken` and line number 62 `auth()->user()->tokens()->delete();`. 

Showing error like : Undefined method 'createToken' and 'tokens'.

However, I fixed that by removing that two methods and it is working. But, In **Postman** the token after logging is **null**. Does this impact the code? Please review it.

**Comment by habibmhamadi** [comment]
@codersangam It's because you didn't install & configure sanctum properly.
make sure you published the configuration files and run migration. and also use HasApiTokens in your user model.

**Comment by habibmhamadi** [comment]
This is not an issue so closing it. and if you cloned this repo then don't forget to run composer install first.

**Comment by codersangam** [comment]
I followed the tutorials and got error. And I didn't clone. My repo: https://github.com/codersangam/flutter_plus_laravel_blog
However I fixed myself. Thanks for the tuts.
